\ir ./add_user.sql
\ir ./change_password.sql
\ir ./change_phase.sql
\ir ./config.sql
\ir ./config_update.sql
\ir ./delete_user.sql
\ir ./get_page.sql
\ir ./ideas_space_user.sql
\ir ./quorum_info.sql
\ir ./school_listing.sql
\ir ./update_page.sql
\ir ./update_user.sql
\ir ./user_listing.sql
\ir ./vote.sql
