\ir change_password.sql
\ir encrypt_pass.sql
\ir is_admin.sql
\ir is_owner.sql
\ir from_school.sql
\ir jwt_token.sql
\ir login.sql
\ir logout.sql
\ir me.sql
\ir check_user.sql
\ir refresh_token.sql
\ir user_id.sql
\ir permissions.sql
\ir db_access.sql
