\ir change_password.sql
\ir encrypt_pass.sql
\ir is_admin.sql
\ir is_owner.sql
\ir is_moderator.sql
\ir is_principal.sql
\ir has_role_comment.sql
\ir from_school.sql
\ir from_space.sql
\ir jwt_token.sql
\ir login.sql
\ir logout.sql
\ir me.sql
\ir check_user.sql
\ir refresh_token.sql
\ir reset_password.sql
\ir user_id.sql
